version: "3.3"
services:
  node:
    build: .
    image: stakecamp/elrdnode:latest
    ports:
      - "8080:8080"
    volumes: 
      - ${ELROND_MOUNT_VOLUME}:/data
    labels:
      com.datadoghq.ad.logs: '[{"source": "node", "service": "node"}]'

  datadog:
    image: gcr.io/datadoghq/agent:7
    environment: 
      DD_API_KEY: ${DD_API_KEY}
      DD_SITE: datadoghq.eu
      DD_LOGS_ENABLED: 'true'
      DD_LOGS_CONFIG_DOCKER_CONTAINER_USE_FILE: 'true' 
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /proc/:/host/proc/:ro
      - /opt/datadog-agent/run:/opt/datadog-agent/run:rw
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro

  autoheal:
    image: willfarrell/autoheal
    restart: always
    environment: 
      DOCKER_SOCK: /var/run/docker.sock
      AUTOHEAL_CONTAINER_LABEL: all
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      com.datadoghq.ad.logs: '[{"source": "autoheal", "service": "autoheal"}]'

  watchtower:
    image: containrrr/watchtower
    restart: always
    command: --interval 120
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      com.datadoghq.ad.logs: '[{"source": "watchtower", "service": "watchtower"}]'
  
