package main

type StatusMetrics struct {
	ErdCurrentBlockSize                            int    `json:"erd_current_block_size"`
	ErdNoncesPassedInCurrentEpoch                  int    `json:"erd_nonces_passed_in_current_epoch"`
	ErdGasPriceModifierEnableEpoch                 int    `json:"erd_gas_price_modifier_enable_epoch"`
	ErdSynchronizedRound                           int    `json:"erd_synchronized_round"`
	ErdConnectedNodes                              int    `json:"erd_connected_nodes"`
	ErdDoubleKeyProtectionEnableEpoch              int    `json:"erd_double_key_protection_enable_epoch"`
	ErdGovernanceEnableEpoch                       int    `json:"erd_governance_enable_epoch"`
	ErdNetworkSentBps                              int    `json:"erd_network_sent_bps"`
	ErdMemUsedGolang                               int    `json:"erd_mem_used_golang"`
	ErdNumShardHeadersProcessed                    int    `json:"erd_num_shard_headers_processed"`
	ErdNumValidators                               int    `json:"erd_num_validators"`
	ErdMiniBlocksSize                              int    `json:"erd_mini_blocks_size"`
	ErdRewardsTopUpGradientPoint                   string `json:"erd_rewards_top_up_gradient_point"`
	ErdNumAccountsStateCheckpoints                 int    `json:"erd_num_accounts_state_checkpoints"`
	ErdMinGasPrice                                 int    `json:"erd_min_gas_price"`
	ErdNumTxBlock                                  int    `json:"erd_num_tx_block"`
	ErdCorrectLastUnjailedEnableEpoch              int    `json:"erd_correct_last_unjailed_enable_epoch"`
	ErdDenomination                                int    `json:"erd_denomination"`
	ErdForkChoiceCount                             int    `json:"erd_fork_choice_count"`
	ErdNetworkRecvBytesInEpochPerHost              int64  `json:"erd_network_recv_bytes_in_epoch_per_host"`
	ErdStartTime                                   int    `json:"erd_start_time"`
	ErdNumConnectedPeers                           int    `json:"erd_num_connected_peers"`
	ErdIncrementScrNonceInMultiTransferEnableEpoch int    `json:"erd_increment_scr_nonce_in_multi_transfer_enable_epoch"`
	ErdRepairCallbackEnableEpoch                   int    `json:"erd_repair_callback_enable_epoch"`
	ErdCurrentBlockHash                            string `json:"erd_current_block_hash"`
	ErdAheadOfTimeGasUsageEnableEpoch              int    `json:"erd_ahead_of_time_gas_usage_enable_epoch"`
	ErdMemUsedSys                                  int64  `json:"erd_mem_used_sys"`
	ErdNumPeerStateCheckpoints                     int    `json:"erd_num_peer_state_checkpoints"`
	ErdNumShardsWithoutMeta                        int    `json:"erd_num_shards_without_meta"`
	ErdReturnDataToLastTransferEnableEpoch         int    `json:"erd_return_data_to_last_transfer_enable_epoch"`
	ErdCountConsensusAcceptedBlocks                int    `json:"erd_count_consensus_accepted_blocks"`
	ErdNodeType                                    string `json:"erd_node_type"`
	ErdNetworkRecvBpsPeak                          int    `json:"erd_network_recv_bps_peak"`
	ErdNonceAtEpochStart                           int    `json:"erd_nonce_at_epoch_start"`
	ErdNumMetachainNodes                           int    `json:"erd_num_metachain_nodes"`
	ErdNumMiniBlocks                               int    `json:"erd_num_mini_blocks"`
	ErdRoundsPassedInCurrentEpoch                  int    `json:"erd_rounds_passed_in_current_epoch"`
	ErdEsdtEnableEpoch                             int    `json:"erd_esdt_enable_epoch"`
	ErdNumShardHeadersFromPool                     int    `json:"erd_num_shard_headers_from_pool"`
	ErdStakeEnableEpoch                            int    `json:"erd_stake_enable_epoch"`
	ErdLiveValidatorNodes                          int    `json:"erd_live_validator_nodes"`
	ErdCrossCheckBlockHeight                       string `json:"erd_cross_check_block_height"`
	ErdTopUpFactor                                 string `json:"erd_top_up_factor"`
	ErdCurrentRoundTimestamp                       int    `json:"erd_current_round_timestamp"`
	ErdNetworkSentBytesInEpochPerHost              int64  `json:"erd_network_sent_bytes_in_epoch_per_host"`
	ErdChainID                                     string `json:"erd_chain_id"`
	ErdGasPerDataByte                              int    `json:"erd_gas_per_data_byte"`
	ErdDevRewards                                  string `json:"erd_dev_rewards"`
	ErdHighestFinalNonce                           int    `json:"erd_highest_final_nonce"`
	ErdMemTotal                                    int64  `json:"erd_mem_total"`
	ErdPenalizedTooMuchGasEnableEpoch              int    `json:"erd_penalized_too_much_gas_enable_epoch"`
	ErdDelegationManagerEnableEpoch                int    `json:"erd_delegation_manager_enable_epoch"`
	ErdNetworkRecvPercent                          int    `json:"erd_network_recv_percent"`
	ErdNodeDisplayName                             string `json:"erd_node_display_name"`
	ErdPublicKeyBlockSign                          string `json:"erd_public_key_block_sign"`
	ErdNumTransactionsProcessed                    int    `json:"erd_num_transactions_processed"`
	ErdRedelegateBelowMinCheckEnableEpoch          int    `json:"erd_redelegate_below_min_check_enable_epoch"`
	ErdCurrentRound                                int    `json:"erd_current_round"`
	ErdMetaConsensusGroupSize                      int    `json:"erd_meta_consensus_group_size"`
	ErdEsdtTransferRoleEnableEpoch                 int    `json:"erd_esdt_transfer_role_enable_epoch"`
	ErdDelegationSmartContractEnableEpoch          int    `json:"erd_delegation_smart_contract_enable_epoch"`
	ErdShardConsensusGroupSize                     int    `json:"erd_shard_consensus_group_size"`
	ErdConsensusRoundState                         string `json:"erd_consensus_round_state"`
	ErdLeaderPercentage                            string `json:"erd_leader_percentage"`
	ErdMaxGasPerTransaction                        int    `json:"erd_max_gas_per_transaction"`
	ErdConsensusProcessedProposedBlock             int    `json:"erd_consensus_processed_proposed_block"`
	ErdAppVersion                                  string `json:"erd_app_version"`
	ErdBelowSignedThresholdEnableEpoch             int    `json:"erd_below_signed_threshold_enable_epoch"`
	ErdRelayedTransactionsEnableEpoch              int    `json:"erd_relayed_transactions_enable_epoch"`
	ErdTotalSupply                                 string `json:"erd_total_supply"`
	ErdTxPoolLoad                                  int    `json:"erd_tx_pool_load"`
	ErdCountAcceptedBlocks                         int    `json:"erd_count_accepted_blocks"`
	ErdGlobalMintBurnDisableEpoch                  int    `json:"erd_global_mint_burn_disable_epoch"`
	ErdInflation                                   string `json:"erd_inflation"`
	ErdNetworkSentPercent                          int    `json:"erd_network_sent_percent"`
	ErdCountConsensus                              int    `json:"erd_count_consensus"`
	ErdRoundAtEpochStart                           int    `json:"erd_round_at_epoch_start"`
	ErdNumConnectedPeersClassification             string `json:"erd_num_connected_peers_classification"`
	ErdSaveJailedAlwaysEnableEpoch                 int    `json:"erd_save_jailed_always_enable_epoch"`
	ErdNonce                                       int    `json:"erd_nonce"`
	ErdIsSyncing                                   int    `json:"erd_is_syncing"`
	ErdEpochNumber                                 int    `json:"erd_epoch_number"`
	ErdBlockGasAndFeeRecheckEnableEpoch            int    `json:"erd_block_gas_and_fee_recheck_enable_epoch"`
	ErdMinTransactionVersion                       int    `json:"erd_min_transaction_version"`
	ErdStakingV2EnableEpoch                        int    `json:"erd_staking_v2_enable_epoch"`
	ErdSwitchJailWaitingEnableEpoch                int    `json:"erd_switch_jail_waiting_enable_epoch"`
	ErdRoundsPerEpoch                              int    `json:"erd_rounds_per_epoch"`
	ErdGasPriceModifier                            string `json:"erd_gas_price_modifier"`
	ErdSenderInOutTransferEnableEpoch              int    `json:"erd_sender_in_out_transfer_enable_epoch"`
	ErdShardID                                     int    `json:"erd_shard_id"`
	ErdProbableHighestNonce                        int    `json:"erd_probable_highest_nonce"`
	ErdPeerSubtype                                 string `json:"erd_peer_subtype"`
	ErdConsensusState                              string `json:"erd_consensus_state"`
	ErdRoundTime                                   int    `json:"erd_round_time"`
	ErdLatestTagSoftwareVersion                    string `json:"erd_latest_tag_software_version"`
	ErdBuiltInFunctionsEnableEpoch                 int    `json:"erd_built_in_functions_enable_epoch"`
	ErdTotalFees                                   string `json:"erd_total_fees"`
	ErdEsdtMultiTransferEnableEpoch                int    `json:"erd_esdt_multi_transfer_enable_epoch"`
	ErdMetaProtectionEnableEpoch                   int    `json:"erd_meta_protection_enable_epoch"`
	ErdMemLoadPercent                              int    `json:"erd_mem_load_percent"`
	ErdEpochForEconomicsData                       int    `json:"erd_epoch_for_economics_data"`
	ErdRelayedTransactionsV2EnableEpoch            int    `json:"erd_relayed_transactions_v2_enable_epoch"`
	ErdTransactionSignedWithTxhashEnableEpoch      int    `json:"erd_transaction_signed_with_txhash_enable_epoch"`
	ErdBuiltinFunctionOnMetaEnableEpoch            int    `json:"erd_builtin_function_on_meta_enable_epoch"`
	ErdMemStackInuse                               int    `json:"erd_mem_stack_inuse"`
	ErdValidatorToDelegationEnableEpoch            int    `json:"erd_validator_to_delegation_enable_epoch"`
	ErdNumNodesInShard                             int    `json:"erd_num_nodes_in_shard"`
	ErdConsensusReceivedProposedBlock              int    `json:"erd_consensus_received_proposed_block"`
	ErdSwitchHysteresisForMinNodesEnableEpoch      int    `json:"erd_switch_hysteresis_for_min_nodes_enable_epoch"`
	ErdConsensusGroupSize                          int    `json:"erd_consensus_group_size"`
	ErdCpuLoadPercent                              int    `json:"erd_cpu_load_percent"`
	ErdUnbondTokensV2EnableEpoch                   int    `json:"erd_unbond_tokens_v2_enable_epoch"`
	ErdMinGasLimit                                 int    `json:"erd_min_gas_limit"`
	ErdRoundDuration                               int    `json:"erd_round_duration"`
	ErdMemHeapInuse                                int    `json:"erd_mem_heap_inuse"`
	ErdNetworkSentBpsPeak                          int    `json:"erd_network_sent_bps_peak"`
	ErdNetworkRecvBps                              int    `json:"erd_network_recv_bps"`
	ErdPeerType                                    string `json:"erd_peer_type"`
	ErdSmartContractDeployEnableEpoch              int    `json:"erd_smart_contract_deploy_enable_epoch"`
	ErdCountLeader                                 int    `json:"erd_count_leader"`
	ErdBalanceWaitingListsEnableEpoch              int    `json:"erd_balance_waiting_lists_enable_epoch"`
	// the following fields are not in the JSON response
	Error string `json:"error"`
}

type StatusResponse struct {
	Data struct {
		Metrics StatusMetrics `json:"metrics"`
	} `json:"data"`
	Error string `json:"error"`
	Code  string `json:"code"`
}
